adding PageLayout and examples
adafruit/Adafruit_CircuitPython_DisplayIO_Layout pull request #69
Opened 2022-03-26 20:10 UTC by FoamyGuy

A new type of layout that allows you to organize your UI into pages that you can change between using name, index, or prev/next functions.

2022-03-27 12:33 UTC, rsbohn requested changes

2022-03-27 12:33 UTC, rsbohn commented on adafruit_displayio_layout/layouts/page_layout.py
> +        if page_index:
This should be `if page_index is not None:`

2022-03-27 12:33 UTC, rsbohn commented on adafruit_displayio_layout/layouts/page_layout.py
> +        if page_name:
This should be `if page_name is not None:`

2022-03-27 13:45 UTC, rsbohn commented
Consider adding a property to retrieve the current page content:

    showing_page_content -> Displayable

Make it easy for the user to retrieve the object they added using `add_content()` without any wrappers.

The user shouldn't need to know about `_page_group` and `sub_view_obj`, these are implementation details.

2022-03-28 17:25 UTC, FoamyGuy commented on adafruit_displayio_layout/layouts/page_layout.py
> +        if page_index:
Good catch thank you. Fixed with latest commit

2022-03-28 17:25 UTC, FoamyGuy commented on adafruit_displayio_layout/layouts/page_layout.py
> +        if page_name:
Good catch thank you. Fixed with latest commit

2022-03-28 17:27 UTC, FoamyGuy commented
> Consider adding a property to retrieve the current page content:
> 
> ```
> showing_page_content -> Displayable
> ```
> 
> Make it easy for the user to retrieve the object they added using `add_content()` without any wrappers.
> 
> The user shouldn't need to know about `_page_group` and `sub_view_obj`, these are implementation details.

Good idea, I like that functionality.  Thanks for trying this out and suggesting improvements. I'll add another commit with this new property

2022-03-28 17:31 UTC, FoamyGuy commented
Also I like the idea of a `Displayable` typing protocol (I think that is the right term). Lots of functions can accept this type of argument. Originally TileGrid and Group were the only that existed but now the vectorio shapes exist and are similar. Having this type defined somewhere will allow us to more easily update it if we end up adding any more types that can be shown directly like this.

2022-03-28 17:39 UTC, FoamyGuy commented
Latest commit adds the `showing_page_content` property as well as an illustration of it's usage in the advanced example script

2022-03-28 17:42 UTC, FoamyGuy commented
Not sure of the cause of CI failure. It passes locally for me:
![image](https://user-images.githubusercontent.com/2406189/160456037-da96098e-2859-4490-9afe-749d62f45683.png)

Will look into this a bit later on today.

2022-03-28 21:00 UTC, FoamyGuy commented
I think this is the root caused of the CI failure. https://github.com/psf/black/issues/2964 Looks like there are a few options to get past it but it might be something we'll need to decided on across all of the libraries if I am understanding correctly.

2022-03-29 15:48 UTC, FoamyGuy commented
Indeed the Black / Click version issue is what was causing CI to fail. There was a commit yesterday to change the version used and I just re-ran the jobs and now it's passing :tada:

2022-04-08 00:42 UTC, aioue commented
**LGTM.**

Tested code on a Titano successfully.

Test process:
- Loaded `page_layout.py` onto a Titano
- Ran the 2 test files using adapted import line `from page_layout import PageLayout` (hobbyist python user)

Test results:
- `simpletest` PASS. Rendered both pages successfully and switches between them.
- `advancedtest` PASS. Rendered all three pages successfully and modifies the second page as expected.

Notes:
- Feels faster to load the code and render the text and shapes than other Learning System templates 🚀  Nice work FoamyGuy 👏

2022-04-09 16:46 UTC, merged